# PS3 - Shopping_Revenue

## Problem Statement

Predicting Shopping Mall Sales. You will have to create model to predict revenue. Identify the model with best params. 

Target Column - Revenue.

Data Link - https://github.com/edyoda/data-science-complete-tutorial/blob/master/Data/Shopping_Revenue.csv

# Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Getting Data

In [2]:
data = pd.read_csv(r"C:\Users\HP\Desktop\Kowshik\Shopping_Revenue.csv")
data

,Id,Open Date,City,City Group,Type,P1,P2,P3,P4,P5,...,P29,P30,P31,P32,P33,P34,P35,P36,P37,revenue
0,0,7/17/1999,İstanbul,Big Cities,IL,4,5.0,4.0,4.0,2,...,3.0,5,3,4,5,5,4,3,4,5653753
1,1,2/14/2008,Ankara,Big Cities,FC,4,5.0,4.0,4.0,1,...,3.0,0,0,0,0,0,0,0,0,6923131
2,2,3/9/2013,Diyarbakır,Other,IL,2,4.0,2.0,5.0,2,...,3.0,0,0,0,0,0,0,0,0,2055379
3,3,2/2/2012,Tokat,Other,IL,6,4.5,6.0,6.0,4,...,7.5,25,12,10,6,18,12,12,6,2675511
4,4,5/9/2009,Gaziantep,Other,IL,3,4.0,3.0,4.0,2,...,3.0,5,1,3,2,3,4,3,3,4316715
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,132,6/25/2008,Trabzon,Other,FC,2,3.0,3.0,5.0,4,...,3.0,0,0,0,0,0,0,0,0,5787594
133,133,10/12/2006,İzmir,Big Cities,FC,4,5.0,4.0,4.0,2,...,3.0,0,0,0,0,0,0,0,0,9262754
134,134,7/8/2006,Kayseri,Other,FC,3,4.0,4.0,4.0,2,...,3.0,0,0,0,0,0,0,0,0,2544857
135,135,10/29/2010,İstanbul,Big Cities,FC,4,5.0,4.0,5.0,2,...,3.0,0,0,0,0,0,0,0,0,7217634
136,136,9/1/2009,İstanbul,Big Cities,FC,4,5.0,3.0,5.0,2,...,3.0,0,0,0,0,0,0,0,0,6363241

* in above data, open date column as incorrect format.
* finally, i conclude to set right format to date function.
* previously,date format is MM-DD-YYYY.
* now,i am changing the format to YYYY-MM-DD.

In [3]:
data["Open Date"] = pd.to_datetime(data["Open Date"]).dt.date

In [4]:
data

,Id,Open Date,City,City Group,Type,P1,P2,P3,P4,P5,...,P29,P30,P31,P32,P33,P34,P35,P36,P37,revenue
0,0,1999-07-17,İstanbul,Big Cities,IL,4,5.0,4.0,4.0,2,...,3.0,5,3,4,5,5,4,3,4,5653753
1,1,2008-02-14,Ankara,Big Cities,FC,4,5.0,4.0,4.0,1,...,3.0,0,0,0,0,0,0,0,0,6923131
2,2,2013-03-09,Diyarbakır,Other,IL,2,4.0,2.0,5.0,2,...,3.0,0,0,0,0,0,0,0,0,2055379
3,3,2012-02-02,Tokat,Other,IL,6,4.5,6.0,6.0,4,...,7.5,25,12,10,6,18,12,12,6,2675511
4,4,2009-05-09,Gaziantep,Other,IL,3,4.0,3.0,4.0,2,...,3.0,5,1,3,2,3,4,3,3,4316715
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,132,2008-06-25,Trabzon,Other,FC,2,3.0,3.0,5.0,4,...,3.0,0,0,0,0,0,0,0,0,5787594
133,133,2006-10-12,İzmir,Big Cities,FC,4,5.0,4.0,4.0,2,...,3.0,0,0,0,0,0,0,0,0,9262754
134,134,2006-07-08,Kayseri,Other,FC,3,4.0,4.0,4.0,2,...,3.0,0,0,0,0,0,0,0,0,2544857
135,135,2010-10-29,İstanbul,Big Cities,FC,4,5.0,4.0,5.0,2,...,3.0,0,0,0,0,0,0,0,0,7217634
136,136,2009-09-01,İstanbul,Big Cities,FC,4,5.0,3.0,5.0,2,...,3.0,0,0,0,0,0,0,0,0,6363241

* it is clearly Regression Problem.
* below steps to implement model.

# Data Inspection

In [5]:
data.shape

(137, 43)

In [6]:
data.columns

Index(['Id', 'Open Date', 'City', 'City Group', 'Type', 'P1', 'P2', 'P3', 'P4',
       'P5', 'P6', 'P7', 'P8', 'P9', 'P10', 'P11', 'P12', 'P13', 'P14', 'P15',
       'P16', 'P17', 'P18', 'P19', 'P20', 'P21', 'P22', 'P23', 'P24', 'P25',
       'P26', 'P27', 'P28', 'P29', 'P30', 'P31', 'P32', 'P33', 'P34', 'P35',
       'P36', 'P37', 'revenue'],
      dtype='object')

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 137 entries, 0 to 136
Data columns (total 43 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Id          137 non-null    int64
 1   Open Date   137 non-null    object
 2   City        137 non-null    object
 3   City Group  137 non-null    object
 4   Type        137 non-null    object
 5   P1          137 non-null    int64
 6   P2          137 non-null    float64
 7   P3          137 non-null    float64
 8   P4          137 non-null    float64
 9   P5          137 non-null    int64
 10  P6          133 non-null    float64
 11  P7          133 non-null    float64
 12  P8          137 non-null    int64
 13  P9          137 non-null    int64
 14  P10         137 non-null    int64
 15  P11         137 non-null    int64
 16  P12         137 non-null    int64
 17  P13         137 non-null    float64
 18  P14         137 non-null    int64
 19  P15         137 non-null    int64
 20  P16         137 non-null    int64
 21  P17         137 non-null    int64
 22  P18         137 non-null    int64
 23  P19         137 non-null    int64
 24  P20         137 non-null    int64
 25  P21         137 non-null    int64
 26  P22         137 non-null    int64
 27  P23         137 non-null    int64
 28  P24         137 non-null    int64
 29  P25         137 non-null    int64
 30  P26         137 non-null    float64
 31  P27         137 non-null    float64
 32  P28         137 non-null    float64
 33  P29         137 non-null    float64
 34  P30         137 non-null    int64
 35  P31         137 non-null    int64
 36  P32         137 non-null    int64
 37  P33         137 non-null    int64
 38  P34         137 non-null    int64
 39  P35         137 non-null    int64
 40  P36         137 non-null    int64
 41  P37         137 non-null    int64
 42  revenue     137 non-null    int64
dtypes: float64(10), int64(29), object(4)
memory usage: 46.1+ KB

In [8]:
data.describe()

,Id,P1,P2,P3,P4,P5,P6,P7,P8,P9,...,P29,P30,P31,P32,P33,P34,P35,P36,P37,revenue
count,137.000000,137.000000,137.000000,137.000000,137.000000,137.000000,133.000000,133.000000,137.000000,137.000000,...,137.000000,137.000000,137.000000,137.000000,137.000000,137.000000,137.000000,137.000000,137.000000,1.370000e+02
mean,68.000000,4.014599,4.408759,4.317518,4.372263,2.007299,3.323308,5.398496,5.153285,5.445255,...,3.135036,2.729927,1.941606,2.525547,1.138686,2.489051,2.029197,2.211679,1.116788,4.453533e+06
std,39.692569,2.910391,1.514900,1.032337,1.016462,1.209620,2.080024,2.296044,1.858567,1.834793,...,1.680887,5.536647,3.512093,5.230117,1.698540,5.165093,3.436272,4.168211,1.790768,2.576072e+06
min,0.000000,1.000000,1.000000,0.000000,3.000000,1.000000,1.000000,1.000000,1.000000,4.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.149870e+06
25%,34.000000,2.000000,4.000000,4.000000,4.000000,1.000000,2.000000,5.000000,4.000000,4.000000,...,2.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.999068e+06
50%,68.000000,3.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,5.000000,5.000000,...,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.939804e+06
75%,102.000000,4.000000,5.000000,5.000000,5.000000,2.000000,4.000000,5.000000,5.000000,5.000000,...,3.000000,4.000000,3.000000,3.000000,2.000000,3.000000,4.000000,3.000000,2.000000,5.166635e+06
max,136.000000,12.000000,7.500000,7.500000,7.500000,8.000000,10.000000,10.000000,10.000000,10.000000,...,7.500000,25.000000,15.000000,25.000000,6.000000,24.000000,15.000000,20.000000,8.000000,1.969694e+07

In [9]:
data.isnull().sum()

Id            0
Open Date     0
City          0
City Group    0
Type          0
P1            0
P2            0
P3            0
P4            0
P5            0
P6            4
P7            4
P8            0
P9            0
P10           0
P11           0
P12           0
P13           0
P14           0
P15           0
P16           0
P17           0
P18           0
P19           0
P20           0
P21           0
P22           0
P23           0
P24           0
P25           0
P26           0
P27           0
P28           0
P29           0
P30           0
P31           0
P32           0
P33           0
P34           0
P35           0
P36           0
P37           0
revenue       0
dtype: int64

* here showing some missing valves.
* now, i am replacing with forward fill method replacing valves.

In [10]:
data["P6"].fillna(method="ffill",inplace=True)
data

,Id,Open Date,City,City Group,Type,P1,P2,P3,P4,P5,...,P29,P30,P31,P32,P33,P34,P35,P36,P37,revenue
0,0,1999-07-17,İstanbul,Big Cities,IL,4,5.0,4.0,4.0,2,...,3.0,5,3,4,5,5,4,3,4,5653753
1,1,2008-02-14,Ankara,Big Cities,FC,4,5.0,4.0,4.0,1,...,3.0,0,0,0,0,0,0,0,0,6923131
2,2,2013-03-09,Diyarbakır,Other,IL,2,4.0,2.0,5.0,2,...,3.0,0,0,0,0,0,0,0,0,2055379
3,3,2012-02-02,Tokat,Other,IL,6,4.5,6.0,6.0,4,...,7.5,25,12,10,6,18,12,12,6,2675511
4,4,2009-05-09,Gaziantep,Other,IL,3,4.0,3.0,4.0,2,...,3.0,5,1,3,2,3,4,3,3,4316715
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,132,2008-06-25,Trabzon,Other,FC,2,3.0,3.0,5.0,4,...,3.0,0,0,0,0,0,0,0,0,5787594
133,133,2006-10-12,İzmir,Big Cities,FC,4,5.0,4.0,4.0,2,...,3.0,0,0,0,0,0,0,0,0,9262754
134,134,2006-07-08,Kayseri,Other,FC,3,4.0,4.0,4.0,2,...,3.0,0,0,0,0,0,0,0,0,2544857
135,135,2010-10-29,İstanbul,Big Cities,FC,4,5.0,4.0,5.0,2,...,3.0,0,0,0,0,0,0,0,0,7217634
136,136,2009-09-01,İstanbul,Big Cities,FC,4,5.0,3.0,5.0,2,...,3.0,0,0,0,0,0,0,0,0,6363241

In [11]:
data["P7"].fillna(method="ffill",inplace=True)
data

,Id,Open Date,City,City Group,Type,P1,P2,P3,P4,P5,...,P29,P30,P31,P32,P33,P34,P35,P36,P37,revenue
0,0,1999-07-17,İstanbul,Big Cities,IL,4,5.0,4.0,4.0,2,...,3.0,5,3,4,5,5,4,3,4,5653753
1,1,2008-02-14,Ankara,Big Cities,FC,4,5.0,4.0,4.0,1,...,3.0,0,0,0,0,0,0,0,0,6923131
2,2,2013-03-09,Diyarbakır,Other,IL,2,4.0,2.0,5.0,2,...,3.0,0,0,0,0,0,0,0,0,2055379
3,3,2012-02-02,Tokat,Other,IL,6,4.5,6.0,6.0,4,...,7.5,25,12,10,6,18,12,12,6,2675511
4,4,2009-05-09,Gaziantep,Other,IL,3,4.0,3.0,4.0,2,...,3.0,5,1,3,2,3,4,3,3,4316715
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,132,2008-06-25,Trabzon,Other,FC,2,3.0,3.0,5.0,4,...,3.0,0,0,0,0,0,0,0,0,5787594
133,133,2006-10-12,İzmir,Big Cities,FC,4,5.0,4.0,4.0,2,...,3.0,0,0,0,0,0,0,0,0,9262754
134,134,2006-07-08,Kayseri,Other,FC,3,4.0,4.0,4.0,2,...,3.0,0,0,0,0,0,0,0,0,2544857
135,135,2010-10-29,İstanbul,Big Cities,FC,4,5.0,4.0,5.0,2,...,3.0,0,0,0,0,0,0,0,0,7217634
136,136,2009-09-01,İstanbul,Big Cities,FC,4,5.0,3.0,5.0,2,...,3.0,0,0,0,0,0,0,0,0,6363241

In [12]:
data.isnull().sum()

Id            0
Open Date     0
City          0
City Group    0
Type          0
P1            0
P2            0
P3            0
P4            0
P5            0
P6            0
P7            0
P8            0
P9            0
P10           0
P11           0
P12           0
P13           0
P14           0
P15           0
P16           0
P17           0
P18           0
P19           0
P20           0
P21           0
P22           0
P23           0
P24           0
P25           0
P26           0
P27           0
P28           0
P29           0
P30           0
P31           0
P32           0
P33           0
P34           0
P35           0
P36           0
P37           0
revenue       0
dtype: int64

In [13]:
data['Year'] = pd.DatetimeIndex(data['Open Date']).year
data['Month'] = pd.DatetimeIndex(data['Open Date']).month
data['Day'] = pd.DatetimeIndex(data['Open Date']).day
data.head()

,Id,Open Date,City,City Group,Type,P1,P2,P3,P4,P5,...,P32,P33,P34,P35,P36,P37,revenue,Year,Month,Day
0,0,1999-07-17,İstanbul,Big Cities,IL,4,5.0,4.0,4.0,2,...,4,5,5,4,3,4,5653753,1999,7,17
1,1,2008-02-14,Ankara,Big Cities,FC,4,5.0,4.0,4.0,1,...,0,0,0,0,0,0,6923131,2008,2,14
2,2,2013-03-09,Diyarbakır,Other,IL,2,4.0,2.0,5.0,2,...,0,0,0,0,0,0,2055379,2013,3,9
3,3,2012-02-02,Tokat,Other,IL,6,4.5,6.0,6.0,4,...,10,6,18,12,12,6,2675511,2012,2,2
4,4,2009-05-09,Gaziantep,Other,IL,3,4.0,3.0,4.0,2,...,3,2,3,4,3,3,4316715,2009,5,9

* in above data , i will separate year & month & day from open date column.
* so, now i am removing open date column because no use in final class.
* and remove id also for no more use of class.

In [14]:
data.drop(labels="Open Date",axis=1,inplace= True)

In [15]:
data.drop(labels="Id",axis=1,inplace= True)

In [16]:
data

,City,City Group,Type,P1,P2,P3,P4,P5,P6,P7,...,P32,P33,P34,P35,P36,P37,revenue,Year,Month,Day
0,İstanbul,Big Cities,IL,4,5.0,4.0,4.0,2,2.0,5.0,...,4,5,5,4,3,4,5653753,1999,7,17
1,Ankara,Big Cities,FC,4,5.0,4.0,4.0,1,2.0,5.0,...,0,0,0,0,0,0,6923131,2008,2,14
2,Diyarbakır,Other,IL,2,4.0,2.0,5.0,2,3.0,5.0,...,0,0,0,0,0,0,2055379,2013,3,9
3,Tokat,Other,IL,6,4.5,6.0,6.0,4,4.0,10.0,...,10,6,18,12,12,6,2675511,2012,2,2
4,Gaziantep,Other,IL,3,4.0,3.0,4.0,2,2.0,5.0,...,3,2,3,4,3,3,4316715,2009,5,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,Trabzon,Other,FC,2,3.0,3.0,5.0,4,2.0,4.0,...,0,0,0,0,0,0,5787594,2008,6,25
133,İzmir,Big Cities,FC,4,5.0,4.0,4.0,2,3.0,5.0,...,0,0,0,0,0,0,9262754,2006,10,12
134,Kayseri,Other,FC,3,4.0,4.0,4.0,2,3.0,5.0,...,0,0,0,0,0,0,2544857,2006,7,8
135,İstanbul,Big Cities,FC,4,5.0,4.0,5.0,2,2.0,5.0,...,0,0,0,0,0,0,7217634,2010,10,29
136,İstanbul,Big Cities,FC,4,5.0,3.0,5.0,2,2.0,5.0,...,0,0,0,0,0,0,6363241,2009,9,1

* below, i am showing outliers of data.
* clearly, no outliers are involved in data.

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 137 entries, 0 to 136
Data columns (total 44 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City        137 non-null    object
 1   City Group  137 non-null    object
 2   Type        137 non-null    object
 3   P1          137 non-null    int64
 4   P2          137 non-null    float64
 5   P3          137 non-null    float64
 6   P4          137 non-null    float64
 7   P5          137 non-null    int64
 8   P6          137 non-null    float64
 9   P7          137 non-null    float64
 10  P8          137 non-null    int64
 11  P9          137 non-null    int64
 12  P10         137 non-null    int64
 13  P11         137 non-null    int64
 14  P12         137 non-null    int64
 15  P13         137 non-null    float64
 16  P14         137 non-null    int64
 17  P15         137 non-null    int64
 18  P16         137 non-null    int64
 19  P17         137 non-null    int64
 20  P18         137 non-null    int64
 21  P19         137 non-null    int64
 22  P20         137 non-null    int64
 23  P21         137 non-null    int64
 24  P22         137 non-null    int64
 25  P23         137 non-null    int64
 26  P24         137 non-null    int64
 27  P25         137 non-null    int64
 28  P26         137 non-null    float64
 29  P27         137 non-null    float64
 30  P28         137 non-null    float64
 31  P29         137 non-null    float64
 32  P30         137 non-null    int64
 33  P31         137 non-null    int64
 34  P32         137 non-null    int64
 35  P33         137 non-null    int64
 36  P34         137 non-null    int64
 37  P35         137 non-null    int64
 38  P36         137 non-null    int64
 39  P37         137 non-null    int64
 40  revenue     137 non-null    int64
 41  Year        137 non-null    int64
 42  Month       137 non-null    int64
 43  Day         137 non-null    int64
dtypes: float64(10), int64(31), object(3)
memory usage: 47.2+ KB

In [18]:

# creating a dictionary 
# with column name and data type
data_types_dict = {'City': str, 'City Group': str, 'Type': str,'P2': int, 'P3': int, 'P4': int,'P6': int, 'P7': int,'P13': int,
                  'P26': int, 'P27': int,'P28': int, 'P29': int}
  
# we will change the data type 
# of id column to str by giving
# the dict to the astype method
data = data.astype(data_types_dict)
  
# checking the data types
# using df.dtypes method
data.dtypes

City          object
City Group    object
Type          object
P1             int64
P2             int32
P3             int32
P4             int32
P5             int64
P6             int32
P7             int32
P8             int64
P9             int64
P10            int64
P11            int64
P12            int64
P13            int32
P14            int64
P15            int64
P16            int64
P17            int64
P18            int64
P19            int64
P20            int64
P21            int64
P22            int64
P23            int64
P24            int64
P25            int64
P26            int32
P27            int32
P28            int32
P29            int32
P30            int64
P31            int64
P32            int64
P33            int64
P34            int64
P35            int64
P36            int64
P37            int64
revenue        int64
Year           int64
Month          int64
Day            int64
dtype: object

In [19]:
data

,City,City Group,Type,P1,P2,P3,P4,P5,P6,P7,...,P32,P33,P34,P35,P36,P37,revenue,Year,Month,Day
0,İstanbul,Big Cities,IL,4,5,4,4,2,2,5,...,4,5,5,4,3,4,5653753,1999,7,17
1,Ankara,Big Cities,FC,4,5,4,4,1,2,5,...,0,0,0,0,0,0,6923131,2008,2,14
2,Diyarbakır,Other,IL,2,4,2,5,2,3,5,...,0,0,0,0,0,0,2055379,2013,3,9
3,Tokat,Other,IL,6,4,6,6,4,4,10,...,10,6,18,12,12,6,2675511,2012,2,2
4,Gaziantep,Other,IL,3,4,3,4,2,2,5,...,3,2,3,4,3,3,4316715,2009,5,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,Trabzon,Other,FC,2,3,3,5,4,2,4,...,0,0,0,0,0,0,5787594,2008,6,25
133,İzmir,Big Cities,FC,4,5,4,4,2,3,5,...,0,0,0,0,0,0,9262754,2006,10,12
134,Kayseri,Other,FC,3,4,4,4,2,3,5,...,0,0,0,0,0,0,2544857,2006,7,8
135,İstanbul,Big Cities,FC,4,5,4,5,2,2,5,...,0,0,0,0,0,0,7217634,2010,10,29
136,İstanbul,Big Cities,FC,4,5,3,5,2,2,5,...,0,0,0,0,0,0,6363241,2009,9,1

In [20]:
data.columns

Index(['City', 'City Group', 'Type', 'P1', 'P2', 'P3', 'P4', 'P5', 'P6', 'P7',
       'P8', 'P9', 'P10', 'P11', 'P12', 'P13', 'P14', 'P15', 'P16', 'P17',
       'P18', 'P19', 'P20', 'P21', 'P22', 'P23', 'P24', 'P25', 'P26', 'P27',
       'P28', 'P29', 'P30', 'P31', 'P32', 'P33', 'P34', 'P35', 'P36', 'P37',
       'revenue', 'Year', 'Month', 'Day'],
      dtype='object')

# Remove Outliers

In [21]:
Q1 = data.quantile(0.25)
Q3 = data.quantile(0.75)
IQR = Q3 - Q1
IQR

P1               2.0
P2               1.0
P3               1.0
P4               1.0
P5               1.0
P6               2.0
P7               0.0
P8               1.0
P9               1.0
P10              0.0
P11              2.0
P12              1.0
P13              0.0
P14              2.0
P15              2.0
P16              3.0
P17              1.0
P18              4.0
P19              3.0
P20              3.0
P21              2.0
P22              2.0
P23              4.0
P24              2.0
P25              2.0
P26              2.0
P27              2.0
P28              2.0
P29              1.0
P30              4.0
P31              3.0
P32              3.0
P33              2.0
P34              3.0
P35              4.0
P36              3.0
P37              2.0
revenue    2167567.0
Year             4.0
Month            6.0
Day             15.0
dtype: float64

In [22]:
print(data < (Q1 - 1.5 * IQR)) |(data > (Q3 + 1.5 * IQR))

      City  City Group    Day  Month     P1    P10    P11    P12    P13  \
0    False       False  False  False  False  False  False  False  False
1    False       False  False  False  False  False  False  False  False
2    False       False  False  False  False  False  False  False  False
3    False       False  False  False  False  False  False  False  False
4    False       False  False  False  False  False  False  False  False
..     ...         ...    ...    ...    ...    ...    ...    ...    ...
132  False       False  False  False  False   True  False  False   True
133  False       False  False  False  False  False  False  False  False
134  False       False  False  False  False  False  False  False  False
135  False       False  False  False  False  False  False  False  False
136  False       False  False  False  False  False  False  False  False

       P14  ...    P37     P4     P5     P6     P7     P8     P9   Type  \
0    False  ...  False  False  False  False  False  False  False  False
1    False  ...  False  False  False  False  False  False  False  False
2    False  ...  False  False  False  False  False  False  False  False
3    False  ...  False  False  False  False  False  False  False  False
4    False  ...  False  False  False  False  False  False  False  False
..     ...  ...    ...    ...    ...    ...    ...    ...    ...    ...
132  False  ...  False  False  False  False   True  False  False  False
133  False  ...  False  False  False  False  False  False  False  False
134  False  ...  False  False  False  False  False  False  False  False
135  False  ...  False  False  False  False  False  False  False  False
136  False  ...  False  False  False  False  False  False  False  False

      Year  revenue
0     True    False
1    False    False
2    False    False
3    False    False
4    False    False
..     ...      ...
132  False    False
133  False    False
134  False    False
135  False    False
136  False    False

[137 rows x 44 columns]

<ipython-input-22-36f4fb5765a1>:1: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  print(data < (Q1 - 1.5 * IQR)) |(data > (Q3 + 1.5 * IQR))
<ipython-input-22-36f4fb5765a1>:1: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  print(data < (Q1 - 1.5 * IQR)) |(data > (Q3 + 1.5 * IQR))

TypeError: Cannot perform 'ror_' with a dtyped [bool] array and scalar of type [NoneType]

In [23]:
data = data[~((data < (Q1 - 1.5 * IQR)) |(data > (Q3 + 1.5 * IQR))).any(axis=1)]
data.shape

<ipython-input-23-ba54541047be>:1: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  data = data[~((data < (Q1 - 1.5 * IQR)) |(data > (Q3 + 1.5 * IQR))).any(axis=1)]
<ipython-input-23-ba54541047be>:1: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  data = data[~((data < (Q1 - 1.5 * IQR)) |(data > (Q3 + 1.5 * IQR))).any(axis=1)]

(48, 44)

In [24]:
data

,City,City Group,Type,P1,P2,P3,P4,P5,P6,P7,...,P32,P33,P34,P35,P36,P37,revenue,Year,Month,Day
1,Ankara,Big Cities,FC,4,5,4,4,1,2,5,...,0,0,0,0,0,0,6923131,2008,2,14
4,Gaziantep,Other,IL,3,4,3,4,2,2,5,...,3,2,3,4,3,3,4316715,2009,5,9
11,İstanbul,Big Cities,IL,2,4,4,4,2,5,5,...,4,2,3,4,4,2,5161370,2012,5,22
13,İstanbul,Big Cities,FC,4,5,4,4,1,3,5,...,0,0,0,0,0,0,4807746,2010,10,16
17,İstanbul,Big Cities,FC,2,4,4,5,1,3,5,...,0,0,0,0,0,0,8213524,2009,11,8
18,İzmir,Big Cities,IL,4,5,4,3,1,2,5,...,5,4,4,4,3,2,5337526,2012,4,21
25,Eskişehir,Other,FC,4,4,5,5,2,2,5,...,0,0,0,0,0,0,3778621,2011,12,23
31,İstanbul,Big Cities,IL,4,5,4,4,1,3,5,...,3,2,3,4,3,3,2058644,2012,12,31
33,Samsun,Other,FC,2,3,4,4,2,2,5,...,0,0,0,0,0,0,2371202,2013,4,23
34,İstanbul,Big Cities,FC,4,5,4,4,1,3,5,...,0,0,0,0,0,0,4100886,2012,3,21
36,Ankara,Big Cities,FC,3,5,5,3,1,5,5,...,0,0,0,0,0,0,3028267,2008,5,9
37,Ankara,Big Cities,IL,2,3,4,3,1,5,5,...,5,3,4,4,3,1,2740687,2010,8,23
43,Ankara,Big Cities,FC,2,4,5,4,1,2,5,...,0,0,0,0,0,0,2732645,2009,9,24
44,Ankara,Big Cities,IL,2,3,5,3,1,5,5,...,5,2,3,4,3,4,4264176,2004,10,13
46,İzmir,Big Cities,IL,3,5,5,3,1,2,5,...,4,2,2,4,3,3,4250758,2011,8,25
48,Kayseri,Other,FC,4,5,4,4,2,2,5,...,0,0,0,0,0,0,7201784,2011,12,21
53,Samsun,Other,FC,3,4,4,3,1,2,5,...,0,0,0,0,0,0,5595267,2013,3,29
55,İstanbul,Big Cities,FC,2,4,4,4,1,4,5,...,0,0,0,0,0,0,6941173,2008,8,12
57,Antalya,Other,FC,2,3,4,3,1,2,5,...,0,0,0,0,0,0,3258837,2008,6,21
58,İstanbul,Big Cities,FC,3,4,4,5,2,2,5,...,0,0,0,0,0,0,3004429,2012,4,11
59,İstanbul,Big Cities,FC,4,5,4,4,1,3,5,...,0,0,0,0,0,0,3600467,2007,12,1
65,İzmir,Big Cities,FC,3,5,4,3,1,2,5,...,0,0,0,0,0,0,1756069,2013,12,21
70,İstanbul,Big Cities,FC,4,5,4,4,1,4,5,...,0,0,0,0,0,0,3982767,2006,11,27
72,İzmir,Big Cities,IL,3,5,4,4,2,2,5,...,3,2,3,4,3,1,2525375,2009,8,5
79,Adana,Other,IL,4,5,4,3,1,3,5,...,5,3,3,4,4,3,6313221,2010,1,25
80,İstanbul,Big Cities,FC,4,5,4,5,1,3,5,...,0,0,0,0,0,0,3727364,2009,10,16
81,İstanbul,Big Cities,FC,2,4,4,4,1,3,5,...,0,0,0,0,0,0,4066618,2005,12,16
84,İzmir,Big Cities,IL,4,4,5,3,1,3,5,...,3,2,4,4,3,1,4250553,2009,10,9
86,Bursa,Other,FC,3,3,4,4,2,5,5,...,0,0,0,0,0,0,3351383,2011,7,26
91,Bursa,Other,IL,3,5,4,4,1,2,5,...,0,0,0,0,0,0,2083447,2007,6,20
93,Tekirdağ,Other,IL,3,4,4,4,1,2,5,...,4,3,4,5,5,3,3410878,2012,10,14
94,Samsun,Other,FC,2,3,4,4,2,2,5,...,3,4,4,4,3,5,3753720,2011,8,8
95,Samsun,Other,FC,2,4,4,4,2,2,5,...,0,0,0,0,0,0,1270499,2012,6,8
103,Tekirdağ,Other,FC,2,4,4,4,1,2,5,...,0,0,0,0,0,0,4429512,2011,12,6
104,Adana,Other,IL,4,5,4,3,1,3,5,...,3,3,5,4,3,2,4467728,2007,1,22
111,Kütahya,Other,FC,2,3,4,4,2,1,5,...,0,0,0,0,0,0,2993069,2012,8,10
113,Tekirdağ,Other,FC,3,4,4,4,1,2,5,...,0,0,0,0,0,0,2097022,2006,12,9
114,Eskişehir,Other,IL,4,5,5,4,2,2,5,...,3,2,3,4,3,1,4155435,2008,12,6
119,İstanbul,Big Cities,IL,4,5,4,4,2,3,5,...,0,0,0,0,0,0,3780019,2014,1,3
120,Aydın,Other,FC,2,3,4,4,2,2,5,...,0,0,0,0,0,0,4067566,2011,8,18
126,Isparta,Other,IL,3,3,4,4,2,2,5,...,5,4,2,5,3,2,4015749,2008,7,20
127,Bursa,Other,FC,3,4,4,4,2,2,5,...,0,0,0,0,0,0,7592272,2007,9,7
128,Ankara,Big Cities,FC,2,4,4,4,1,2,5,...,0,0,0,0,0,0,2383840,2011,10,14
129,Eskişehir,Other,FC,4,5,5,4,2,2,5,...,0,0,0,0,0,0,3939804,2007,2,8
130,Osmaniye,Other,FC,3,4,3,4,2,1,5,...,0,0,0,0,0,0,3376145,2011,10,29
134,Kayseri,Other,FC,3,4,4,4,2,3,5,...,0,0,0,0,0,0,2544857,2006,7,8
135,İstanbul,Big Cities,FC,4,5,4,5,2,2,5,...,0,0,0,0,0,0,7217634,2010,10,29
136,İstanbul,Big Cities,FC,4,5,3,5,2,2,5,...,0,0,0,0,0,0,6363241,2009,9,1

In [25]:
data["City"].value_counts()

İstanbul     14
Ankara        6
İzmir         5
Samsun        4
Tekirdağ      3
Bursa         3
Eskişehir     3
Adana         2
Kayseri       2
Antalya       1
Isparta       1
Aydın         1
Osmaniye      1
Gaziantep     1
Kütahya       1
Name: City, dtype: int64

In [26]:
data["City Group"].value_counts()

Big Cities    25
Other         23
Name: City Group, dtype: int64

In [27]:
data["Type"].value_counts()

FC    32
IL    16
Name: Type, dtype: int64

# Encoding Categorical Data

In [28]:
data

,City,City Group,Type,P1,P2,P3,P4,P5,P6,P7,...,P32,P33,P34,P35,P36,P37,revenue,Year,Month,Day
1,Ankara,Big Cities,FC,4,5,4,4,1,2,5,...,0,0,0,0,0,0,6923131,2008,2,14
4,Gaziantep,Other,IL,3,4,3,4,2,2,5,...,3,2,3,4,3,3,4316715,2009,5,9
11,İstanbul,Big Cities,IL,2,4,4,4,2,5,5,...,4,2,3,4,4,2,5161370,2012,5,22
13,İstanbul,Big Cities,FC,4,5,4,4,1,3,5,...,0,0,0,0,0,0,4807746,2010,10,16
17,İstanbul,Big Cities,FC,2,4,4,5,1,3,5,...,0,0,0,0,0,0,8213524,2009,11,8
18,İzmir,Big Cities,IL,4,5,4,3,1,2,5,...,5,4,4,4,3,2,5337526,2012,4,21
25,Eskişehir,Other,FC,4,4,5,5,2,2,5,...,0,0,0,0,0,0,3778621,2011,12,23
31,İstanbul,Big Cities,IL,4,5,4,4,1,3,5,...,3,2,3,4,3,3,2058644,2012,12,31
33,Samsun,Other,FC,2,3,4,4,2,2,5,...,0,0,0,0,0,0,2371202,2013,4,23
34,İstanbul,Big Cities,FC,4,5,4,4,1,3,5,...,0,0,0,0,0,0,4100886,2012,3,21
36,Ankara,Big Cities,FC,3,5,5,3,1,5,5,...,0,0,0,0,0,0,3028267,2008,5,9
37,Ankara,Big Cities,IL,2,3,4,3,1,5,5,...,5,3,4,4,3,1,2740687,2010,8,23
43,Ankara,Big Cities,FC,2,4,5,4,1,2,5,...,0,0,0,0,0,0,2732645,2009,9,24
44,Ankara,Big Cities,IL,2,3,5,3,1,5,5,...,5,2,3,4,3,4,4264176,2004,10,13
46,İzmir,Big Cities,IL,3,5,5,3,1,2,5,...,4,2,2,4,3,3,4250758,2011,8,25
48,Kayseri,Other,FC,4,5,4,4,2,2,5,...,0,0,0,0,0,0,7201784,2011,12,21
53,Samsun,Other,FC,3,4,4,3,1,2,5,...,0,0,0,0,0,0,5595267,2013,3,29
55,İstanbul,Big Cities,FC,2,4,4,4,1,4,5,...,0,0,0,0,0,0,6941173,2008,8,12
57,Antalya,Other,FC,2,3,4,3,1,2,5,...,0,0,0,0,0,0,3258837,2008,6,21
58,İstanbul,Big Cities,FC,3,4,4,5,2,2,5,...,0,0,0,0,0,0,3004429,2012,4,11
59,İstanbul,Big Cities,FC,4,5,4,4,1,3,5,...,0,0,0,0,0,0,3600467,2007,12,1
65,İzmir,Big Cities,FC,3,5,4,3,1,2,5,...,0,0,0,0,0,0,1756069,2013,12,21
70,İstanbul,Big Cities,FC,4,5,4,4,1,4,5,...,0,0,0,0,0,0,3982767,2006,11,27
72,İzmir,Big Cities,IL,3,5,4,4,2,2,5,...,3,2,3,4,3,1,2525375,2009,8,5
79,Adana,Other,IL,4,5,4,3,1,3,5,...,5,3,3,4,4,3,6313221,2010,1,25
80,İstanbul,Big Cities,FC,4,5,4,5,1,3,5,...,0,0,0,0,0,0,3727364,2009,10,16
81,İstanbul,Big Cities,FC,2,4,4,4,1,3,5,...,0,0,0,0,0,0,4066618,2005,12,16
84,İzmir,Big Cities,IL,4,4,5,3,1,3,5,...,3,2,4,4,3,1,4250553,2009,10,9
86,Bursa,Other,FC,3,3,4,4,2,5,5,...,0,0,0,0,0,0,3351383,2011,7,26
91,Bursa,Other,IL,3,5,4,4,1,2,5,...,0,0,0,0,0,0,2083447,2007,6,20
93,Tekirdağ,Other,IL,3,4,4,4,1,2,5,...,4,3,4,5,5,3,3410878,2012,10,14
94,Samsun,Other,FC,2,3,4,4,2,2,5,...,3,4,4,4,3,5,3753720,2011,8,8
95,Samsun,Other,FC,2,4,4,4,2,2,5,...,0,0,0,0,0,0,1270499,2012,6,8
103,Tekirdağ,Other,FC,2,4,4,4,1,2,5,...,0,0,0,0,0,0,4429512,2011,12,6
104,Adana,Other,IL,4,5,4,3,1,3,5,...,3,3,5,4,3,2,4467728,2007,1,22
111,Kütahya,Other,FC,2,3,4,4,2,1,5,...,0,0,0,0,0,0,2993069,2012,8,10
113,Tekirdağ,Other,FC,3,4,4,4,1,2,5,...,0,0,0,0,0,0,2097022,2006,12,9
114,Eskişehir,Other,IL,4,5,5,4,2,2,5,...,3,2,3,4,3,1,4155435,2008,12,6
119,İstanbul,Big Cities,IL,4,5,4,4,2,3,5,...,0,0,0,0,0,0,3780019,2014,1,3
120,Aydın,Other,FC,2,3,4,4,2,2,5,...,0,0,0,0,0,0,4067566,2011,8,18
126,Isparta,Other,IL,3,3,4,4,2,2,5,...,5,4,2,5,3,2,4015749,2008,7,20
127,Bursa,Other,FC,3,4,4,4,2,2,5,...,0,0,0,0,0,0,7592272,2007,9,7
128,Ankara,Big Cities,FC,2,4,4,4,1,2,5,...,0,0,0,0,0,0,2383840,2011,10,14
129,Eskişehir,Other,FC,4,5,5,4,2,2,5,...,0,0,0,0,0,0,3939804,2007,2,8
130,Osmaniye,Other,FC,3,4,3,4,2,1,5,...,0,0,0,0,0,0,3376145,2011,10,29
134,Kayseri,Other,FC,3,4,4,4,2,3,5,...,0,0,0,0,0,0,2544857,2006,7,8
135,İstanbul,Big Cities,FC,4,5,4,5,2,2,5,...,0,0,0,0,0,0,7217634,2010,10,29
136,İstanbul,Big Cities,FC,4,5,3,5,2,2,5,...,0,0,0,0,0,0,6363241,2009,9,1

In [29]:
data["City"].value_counts()

İstanbul     14
Ankara        6
İzmir         5
Samsun        4
Tekirdağ      3
Bursa         3
Eskişehir     3
Adana         2
Kayseri       2
Antalya       1
Isparta       1
Aydın         1
Osmaniye      1
Gaziantep     1
Kütahya       1
Name: City, dtype: int64

In [30]:
data["City Group"].value_counts()

Big Cities    25
Other         23
Name: City Group, dtype: int64

In [31]:
data["Type"].value_counts()

FC    32
IL    16
Name: Type, dtype: int64

In [32]:
data["City"].unique()

array(['Ankara', 'Gaziantep', 'İstanbul', 'İzmir', 'Eskişehir', 'Samsun',
       'Kayseri', 'Antalya', 'Adana', 'Bursa', 'Tekirdağ', 'Kütahya',
       'Aydın', 'Isparta', 'Osmaniye'], dtype=object)

In [33]:
data["City Group"].unique()

array(['Big Cities', 'Other'], dtype=object)

In [34]:
data["Type"].unique()

array(['FC', 'IL'], dtype=object)

In [35]:
data["Type"] = data["Type"].map({'IL':1,'FC':0})

<ipython-input-35-6604cae1014d>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Type"] = data["Type"].map({'IL':1,'FC':0})

In [36]:
data["City Group"] = data["City Group"].map({'Big Cities':0,'Other':1})

<ipython-input-36-0e57bc9f484b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["City Group"] = data["City Group"].map({'Big Cities':0,'Other':1})

In [37]:
data

,City,City Group,Type,P1,P2,P3,P4,P5,P6,P7,...,P32,P33,P34,P35,P36,P37,revenue,Year,Month,Day
1,Ankara,0,0,4,5,4,4,1,2,5,...,0,0,0,0,0,0,6923131,2008,2,14
4,Gaziantep,1,1,3,4,3,4,2,2,5,...,3,2,3,4,3,3,4316715,2009,5,9
11,İstanbul,0,1,2,4,4,4,2,5,5,...,4,2,3,4,4,2,5161370,2012,5,22
13,İstanbul,0,0,4,5,4,4,1,3,5,...,0,0,0,0,0,0,4807746,2010,10,16
17,İstanbul,0,0,2,4,4,5,1,3,5,...,0,0,0,0,0,0,8213524,2009,11,8
18,İzmir,0,1,4,5,4,3,1,2,5,...,5,4,4,4,3,2,5337526,2012,4,21
25,Eskişehir,1,0,4,4,5,5,2,2,5,...,0,0,0,0,0,0,3778621,2011,12,23
31,İstanbul,0,1,4,5,4,4,1,3,5,...,3,2,3,4,3,3,2058644,2012,12,31
33,Samsun,1,0,2,3,4,4,2,2,5,...,0,0,0,0,0,0,2371202,2013,4,23
34,İstanbul,0,0,4,5,4,4,1,3,5,...,0,0,0,0,0,0,4100886,2012,3,21
36,Ankara,0,0,3,5,5,3,1,5,5,...,0,0,0,0,0,0,3028267,2008,5,9
37,Ankara,0,1,2,3,4,3,1,5,5,...,5,3,4,4,3,1,2740687,2010,8,23
43,Ankara,0,0,2,4,5,4,1,2,5,...,0,0,0,0,0,0,2732645,2009,9,24
44,Ankara,0,1,2,3,5,3,1,5,5,...,5,2,3,4,3,4,4264176,2004,10,13
46,İzmir,0,1,3,5,5,3,1,2,5,...,4,2,2,4,3,3,4250758,2011,8,25
48,Kayseri,1,0,4,5,4,4,2,2,5,...,0,0,0,0,0,0,7201784,2011,12,21
53,Samsun,1,0,3,4,4,3,1,2,5,...,0,0,0,0,0,0,5595267,2013,3,29
55,İstanbul,0,0,2,4,4,4,1,4,5,...,0,0,0,0,0,0,6941173,2008,8,12
57,Antalya,1,0,2,3,4,3,1,2,5,...,0,0,0,0,0,0,3258837,2008,6,21
58,İstanbul,0,0,3,4,4,5,2,2,5,...,0,0,0,0,0,0,3004429,2012,4,11
59,İstanbul,0,0,4,5,4,4,1,3,5,...,0,0,0,0,0,0,3600467,2007,12,1
65,İzmir,0,0,3,5,4,3,1,2,5,...,0,0,0,0,0,0,1756069,2013,12,21
70,İstanbul,0,0,4,5,4,4,1,4,5,...,0,0,0,0,0,0,3982767,2006,11,27
72,İzmir,0,1,3,5,4,4,2,2,5,...,3,2,3,4,3,1,2525375,2009,8,5
79,Adana,1,1,4,5,4,3,1,3,5,...,5,3,3,4,4,3,6313221,2010,1,25
80,İstanbul,0,0,4,5,4,5,1,3,5,...,0,0,0,0,0,0,3727364,2009,10,16
81,İstanbul,0,0,2,4,4,4,1,3,5,...,0,0,0,0,0,0,4066618,2005,12,16
84,İzmir,0,1,4,4,5,3,1,3,5,...,3,2,4,4,3,1,4250553,2009,10,9
86,Bursa,1,0,3,3,4,4,2,5,5,...,0,0,0,0,0,0,3351383,2011,7,26
91,Bursa,1,1,3,5,4,4,1,2,5,...,0,0,0,0,0,0,2083447,2007,6,20
93,Tekirdağ,1,1,3,4,4,4,1,2,5,...,4,3,4,5,5,3,3410878,2012,10,14
94,Samsun,1,0,2,3,4,4,2,2,5,...,3,4,4,4,3,5,3753720,2011,8,8
95,Samsun,1,0,2,4,4,4,2,2,5,...,0,0,0,0,0,0,1270499,2012,6,8
103,Tekirdağ,1,0,2,4,4,4,1,2,5,...,0,0,0,0,0,0,4429512,2011,12,6
104,Adana,1,1,4,5,4,3,1,3,5,...,3,3,5,4,3,2,4467728,2007,1,22
111,Kütahya,1,0,2,3,4,4,2,1,5,...,0,0,0,0,0,0,2993069,2012,8,10
113,Tekirdağ,1,0,3,4,4,4,1,2,5,...,0,0,0,0,0,0,2097022,2006,12,9
114,Eskişehir,1,1,4,5,5,4,2,2,5,...,3,2,3,4,3,1,4155435,2008,12,6
119,İstanbul,0,1,4,5,4,4,2,3,5,...,0,0,0,0,0,0,3780019,2014,1,3
120,Aydın,1,0,2,3,4,4,2,2,5,...,0,0,0,0,0,0,4067566,2011,8,18
126,Isparta,1,1,3,3,4,4,2,2,5,...,5,4,2,5,3,2,4015749,2008,7,20
127,Bursa,1,0,3,4,4,4,2,2,5,...,0,0,0,0,0,0,7592272,2007,9,7
128,Ankara,0,0,2,4,4,4,1,2,5,...,0,0,0,0,0,0,2383840,2011,10,14
129,Eskişehir,1,0,4,5,5,4,2,2,5,...,0,0,0,0,0,0,3939804,2007,2,8
130,Osmaniye,1,0,3,4,3,4,2,1,5,...,0,0,0,0,0,0,3376145,2011,10,29
134,Kayseri,1,0,3,4,4,4,2,3,5,...,0,0,0,0,0,0,2544857,2006,7,8
135,İstanbul,0,0,4,5,4,5,2,2,5,...,0,0,0,0,0,0,7217634,2010,10,29
136,İstanbul,0,0,4,5,3,5,2,2,5,...,0,0,0,0,0,0,6363241,2009,9,1

In [38]:
data= pd.get_dummies(data,drop_first=True)

In [39]:
data

,City Group,Type,P1,P2,P3,P4,P5,P6,P7,P8,...,City_Eskişehir,City_Gaziantep,City_Isparta,City_Kayseri,City_Kütahya,City_Osmaniye,City_Samsun,City_Tekirdağ,City_İstanbul,City_İzmir
1,0,0,4,5,4,4,1,2,5,5,...,0,0,0,0,0,0,0,0,0,0
4,1,1,3,4,3,4,2,2,5,5,...,0,1,0,0,0,0,0,0,0,0
11,0,1,2,4,4,4,2,5,5,5,...,0,0,0,0,0,0,0,0,1,0
13,0,0,4,5,4,4,1,3,5,5,...,0,0,0,0,0,0,0,0,1,0
17,0,0,2,4,4,5,1,3,5,4,...,0,0,0,0,0,0,0,0,1,0
18,0,1,4,5,4,3,1,2,5,5,...,0,0,0,0,0,0,0,0,0,1
25,1,0,4,4,5,5,2,2,5,5,...,1,0,0,0,0,0,0,0,0,0
31,0,1,4,5,4,4,1,3,5,5,...,0,0,0,0,0,0,0,0,1,0
33,1,0,2,3,4,4,2,2,5,5,...,0,0,0,0,0,0,1,0,0,0
34,0,0,4,5,4,4,1,3,5,4,...,0,0,0,0,0,0,0,0,1,0
36,0,0,3,5,5,3,1,5,5,5,...,0,0,0,0,0,0,0,0,0,0
37,0,1,2,3,4,3,1,5,5,5,...,0,0,0,0,0,0,0,0,0,0
43,0,0,2,4,5,4,1,2,5,5,...,0,0,0,0,0,0,0,0,0,0
44,0,1,2,3,5,3,1,5,5,5,...,0,0,0,0,0,0,0,0,0,0
46,0,1,3,5,5,3,1,2,5,5,...,0,0,0,0,0,0,0,0,0,1
48,1,0,4,5,4,4,2,2,5,4,...,0,0,0,1,0,0,0,0,0,0
53,1,0,3,4,4,3,1,2,5,5,...,0,0,0,0,0,0,1,0,0,0
55,0,0,2,4,4,4,1,4,5,5,...,0,0,0,0,0,0,0,0,1,0
57,1,0,2,3,4,3,1,2,5,5,...,0,0,0,0,0,0,0,0,0,0
58,0,0,3,4,4,5,2,2,5,5,...,0,0,0,0,0,0,0,0,1,0
59,0,0,4,5,4,4,1,3,5,5,...,0,0,0,0,0,0,0,0,1,0
65,0,0,3,5,4,3,1,2,5,5,...,0,0,0,0,0,0,0,0,0,1
70,0,0,4,5,4,4,1,4,5,5,...,0,0,0,0,0,0,0,0,1,0
72,0,1,3,5,4,4,2,2,5,3,...,0,0,0,0,0,0,0,0,0,1
79,1,1,4,5,4,3,1,3,5,5,...,0,0,0,0,0,0,0,0,0,0
80,0,0,4,5,4,5,1,3,5,5,...,0,0,0,0,0,0,0,0,1,0
81,0,0,2,4,4,4,1,3,5,4,...,0,0,0,0,0,0,0,0,1,0
84,0,1,4,4,5,3,1,3,5,5,...,0,0,0,0,0,0,0,0,0,1
86,1,0,3,3,4,4,2,5,5,4,...,0,0,0,0,0,0,0,0,0,0
91,1,1,3,5,4,4,1,2,5,5,...,0,0,0,0,0,0,0,0,0,0
93,1,1,3,4,4,4,1,2,5,4,...,0,0,0,0,0,0,0,1,0,0
94,1,0,2,3,4,4,2,2,5,5,...,0,0,0,0,0,0,1,0,0,0
95,1,0,2,4,4,4,2,2,5,5,...,0,0,0,0,0,0,1,0,0,0
103,1,0,2,4,4,4,1,2,5,5,...,0,0,0,0,0,0,0,1,0,0
104,1,1,4,5,4,3,1,3,5,5,...,0,0,0,0,0,0,0,0,0,0
111,1,0,2,3,4,4,2,1,5,5,...,0,0,0,0,1,0,0,0,0,0
113,1,0,3,4,4,4,1,2,5,5,...,0,0,0,0,0,0,0,1,0,0
114,1,1,4,5,5,4,2,2,5,4,...,1,0,0,0,0,0,0,0,0,0
119,0,1,4,5,4,4,2,3,5,5,...,0,0,0,0,0,0,0,0,1,0
120,1,0,2,3,4,4,2,2,5,4,...,0,0,0,0,0,0,0,0,0,0
126,1,1,3,3,4,4,2,2,5,4,...,0,0,1,0,0,0,0,0,0,0
127,1,0,3,4,4,4,2,2,5,5,...,0,0,0,0,0,0,0,0,0,0
128,0,0,2,4,4,4,1,2,5,5,...,0,0,0,0,0,0,0,0,0,0
129,1,0,4,5,5,4,2,2,5,4,...,1,0,0,0,0,0,0,0,0,0
130,1,0,3,4,3,4,2,1,5,5,...,0,0,0,0,0,1,0,0,0,0
134,1,0,3,4,4,4,2,3,5,5,...,0,0,0,1,0,0,0,0,0,0
135,0,0,4,5,4,5,2,2,5,5,...,0,0,0,0,0,0,0,0,1,0
136,0,0,4,5,3,5,2,2,5,4,...,0,0,0,0,0,0,0,0,1,0

In [40]:
data.columns

Index(['City Group', 'Type', 'P1', 'P2', 'P3', 'P4', 'P5', 'P6', 'P7', 'P8',
       'P9', 'P10', 'P11', 'P12', 'P13', 'P14', 'P15', 'P16', 'P17', 'P18',
       'P19', 'P20', 'P21', 'P22', 'P23', 'P24', 'P25', 'P26', 'P27', 'P28',
       'P29', 'P30', 'P31', 'P32', 'P33', 'P34', 'P35', 'P36', 'P37',
       'revenue', 'Year', 'Month', 'Day', 'City_Ankara', 'City_Antalya',
       'City_Aydın', 'City_Bursa', 'City_Eskişehir', 'City_Gaziantep',
       'City_Isparta', 'City_Kayseri', 'City_Kütahya', 'City_Osmaniye',
       'City_Samsun', 'City_Tekirdağ', 'City_İstanbul', 'City_İzmir'],
      dtype='object')

# independent & dependent class

In [41]:
x = data.drop("revenue",axis=1)
y = data["revenue"]

In [42]:
x

,City Group,Type,P1,P2,P3,P4,P5,P6,P7,P8,...,City_Eskişehir,City_Gaziantep,City_Isparta,City_Kayseri,City_Kütahya,City_Osmaniye,City_Samsun,City_Tekirdağ,City_İstanbul,City_İzmir
1,0,0,4,5,4,4,1,2,5,5,...,0,0,0,0,0,0,0,0,0,0
4,1,1,3,4,3,4,2,2,5,5,...,0,1,0,0,0,0,0,0,0,0
11,0,1,2,4,4,4,2,5,5,5,...,0,0,0,0,0,0,0,0,1,0
13,0,0,4,5,4,4,1,3,5,5,...,0,0,0,0,0,0,0,0,1,0
17,0,0,2,4,4,5,1,3,5,4,...,0,0,0,0,0,0,0,0,1,0
18,0,1,4,5,4,3,1,2,5,5,...,0,0,0,0,0,0,0,0,0,1
25,1,0,4,4,5,5,2,2,5,5,...,1,0,0,0,0,0,0,0,0,0
31,0,1,4,5,4,4,1,3,5,5,...,0,0,0,0,0,0,0,0,1,0
33,1,0,2,3,4,4,2,2,5,5,...,0,0,0,0,0,0,1,0,0,0
34,0,0,4,5,4,4,1,3,5,4,...,0,0,0,0,0,0,0,0,1,0
36,0,0,3,5,5,3,1,5,5,5,...,0,0,0,0,0,0,0,0,0,0
37,0,1,2,3,4,3,1,5,5,5,...,0,0,0,0,0,0,0,0,0,0
43,0,0,2,4,5,4,1,2,5,5,...,0,0,0,0,0,0,0,0,0,0
44,0,1,2,3,5,3,1,5,5,5,...,0,0,0,0,0,0,0,0,0,0
46,0,1,3,5,5,3,1,2,5,5,...,0,0,0,0,0,0,0,0,0,1
48,1,0,4,5,4,4,2,2,5,4,...,0,0,0,1,0,0,0,0,0,0
53,1,0,3,4,4,3,1,2,5,5,...,0,0,0,0,0,0,1,0,0,0
55,0,0,2,4,4,4,1,4,5,5,...,0,0,0,0,0,0,0,0,1,0
57,1,0,2,3,4,3,1,2,5,5,...,0,0,0,0,0,0,0,0,0,0
58,0,0,3,4,4,5,2,2,5,5,...,0,0,0,0,0,0,0,0,1,0
59,0,0,4,5,4,4,1,3,5,5,...,0,0,0,0,0,0,0,0,1,0
65,0,0,3,5,4,3,1,2,5,5,...,0,0,0,0,0,0,0,0,0,1
70,0,0,4,5,4,4,1,4,5,5,...,0,0,0,0,0,0,0,0,1,0
72,0,1,3,5,4,4,2,2,5,3,...,0,0,0,0,0,0,0,0,0,1
79,1,1,4,5,4,3,1,3,5,5,...,0,0,0,0,0,0,0,0,0,0
80,0,0,4,5,4,5,1,3,5,5,...,0,0,0,0,0,0,0,0,1,0
81,0,0,2,4,4,4,1,3,5,4,...,0,0,0,0,0,0,0,0,1,0
84,0,1,4,4,5,3,1,3,5,5,...,0,0,0,0,0,0,0,0,0,1
86,1,0,3,3,4,4,2,5,5,4,...,0,0,0,0,0,0,0,0,0,0
91,1,1,3,5,4,4,1,2,5,5,...,0,0,0,0,0,0,0,0,0,0
93,1,1,3,4,4,4,1,2,5,4,...,0,0,0,0,0,0,0,1,0,0
94,1,0,2,3,4,4,2,2,5,5,...,0,0,0,0,0,0,1,0,0,0
95,1,0,2,4,4,4,2,2,5,5,...,0,0,0,0,0,0,1,0,0,0
103,1,0,2,4,4,4,1,2,5,5,...,0,0,0,0,0,0,0,1,0,0
104,1,1,4,5,4,3,1,3,5,5,...,0,0,0,0,0,0,0,0,0,0
111,1,0,2,3,4,4,2,1,5,5,...,0,0,0,0,1,0,0,0,0,0
113,1,0,3,4,4,4,1,2,5,5,...,0,0,0,0,0,0,0,1,0,0
114,1,1,4,5,5,4,2,2,5,4,...,1,0,0,0,0,0,0,0,0,0
119,0,1,4,5,4,4,2,3,5,5,...,0,0,0,0,0,0,0,0,1,0
120,1,0,2,3,4,4,2,2,5,4,...,0,0,0,0,0,0,0,0,0,0
126,1,1,3,3,4,4,2,2,5,4,...,0,0,1,0,0,0,0,0,0,0
127,1,0,3,4,4,4,2,2,5,5,...,0,0,0,0,0,0,0,0,0,0
128,0,0,2,4,4,4,1,2,5,5,...,0,0,0,0,0,0,0,0,0,0
129,1,0,4,5,5,4,2,2,5,4,...,1,0,0,0,0,0,0,0,0,0
130,1,0,3,4,3,4,2,1,5,5,...,0,0,0,0,0,1,0,0,0,0
134,1,0,3,4,4,4,2,3,5,5,...,0,0,0,1,0,0,0,0,0,0
135,0,0,4,5,4,5,2,2,5,5,...,0,0,0,0,0,0,0,0,1,0
136,0,0,4,5,3,5,2,2,5,4,...,0,0,0,0,0,0,0,0,1,0

In [43]:
y

1      6923131
4      4316715
11     5161370
13     4807746
17     8213524
18     5337526
25     3778621
31     2058644
33     2371202
34     4100886
36     3028267
37     2740687
43     2732645
44     4264176
46     4250758
48     7201784
53     5595267
55     6941173
57     3258837
58     3004429
59     3600467
65     1756069
70     3982767
72     2525375
79     6313221
80     3727364
81     4066618
84     4250553
86     3351383
91     2083447
93     3410878
94     3753720
95     1270499
103    4429512
104    4467728
111    2993069
113    2097022
114    4155435
119    3780019
120    4067566
126    4015749
127    7592272
128    2383840
129    3939804
130    3376145
134    2544857
135    7217634
136    6363241
Name: revenue, dtype: int64

# Splitting the dataset into the Training set and Test set

In [44]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 1)

In [45]:
x_train.shape

(36, 56)

In [46]:
x_test.shape

(12, 56)

In [47]:
y_train

65     1756069
104    4467728
58     3004429
126    4015749
111    2993069
79     6313221
70     3982767
44     4264176
120    4067566
55     6941173
135    7217634
17     8213524
91     2083447
46     4250758
36     3028267
128    2383840
95     1270499
57     3258837
127    7592272
93     3410878
59     3600467
80     3727364
25     3778621
31     2058644
134    2544857
4      4316715
53     5595267
1      6923131
48     7201784
18     5337526
37     2740687
34     4100886
33     2371202
43     2732645
129    3939804
114    4155435
Name: revenue, dtype: int64

In [48]:
y_test

103    4429512
72     2525375
119    3780019
113    2097022
11     5161370
13     4807746
94     3753720
81     4066618
130    3376145
84     4250553
86     3351383
136    6363241
Name: revenue, dtype: int64

# Regression Algorithm Models

## Linear Regression

In [49]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((36, 56), (12, 56), (36,), (12,))

In [50]:
#Fitting the Simple Linear Regression model to the training dataset  
from sklearn.linear_model import LinearRegression  
regressor= LinearRegression()  
regressor.fit(x_train, y_train)

y_pred = regressor.predict(x_test)

from sklearn.metrics import r2_score
r = r2_score(y_pred,y_test)
r

-0.3184929735927371

## SVM

In [51]:
from sklearn.svm import SVR
classifier = SVR()
classifier.fit(x_train, y_train)

from sklearn.model_selection import GridSearchCV
parameters = [{'C': [0.25, 0.5, 0.75, 1], 'kernel': ['linear']},
              {'C': [0.25, 0.5, 0.75, 1], 'kernel': ['rbf'], 'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]}]
grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search.fit(x_train, y_train)





best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:", best_parameters)

Best Accuracy: nan %
Best Parameters: {'C': 0.25, 'kernel': 'linear'}

c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\sklearn\model_selection\_search.py:922: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan]
  warnings.warn(

## Decision Tree

In [54]:
from sklearn.tree import DecisionTreeRegressor
reg = DecisionTreeRegressor(random_state = 0)
reg.fit(x_train, y_train)

y_pred = reg.predict(x_test)

from sklearn.metrics import r2_score
r = r2_score(y_pred,y_test)
r

0.4706071206259247

## Random Forest

In [55]:
#Fitting the Simple Linear Regression model to the training dataset  
from sklearn.ensemble import RandomForestRegressor 
re= LinearRegression()  
re.fit(x_train, y_train)

y_pred = re.predict(x_test)

from sklearn.metrics import r2_score
r = r2_score(y_pred,y_test)
r

-0.3184929735927371